import base from './catalog.json';
import additions from './catalog-live-additions.json';
import type { Catalog, Product } from '../types';

/**
 * Live-reconciled catalog.
 *
 * `catalog.json` is the checked-in snapshot; `catalog-live-additions.json`
 * contains products that ARE live on the Shopify storefront
 * (store.brainsait.de/products.json) but were missing from the snapshot
 * (generated by scripts/sync-catalog-from-public-storefront.py).
 * Merging here keeps the rendered catalog — and every stat derived from it
 * via getCatalogStats — in sync with the real store without waiting for a
 * full admin-API re-sync of catalog.json.
 */
const baseCatalog = base as unknown as Catalog;
const extra = additions as unknown as {
  templates?: Product[];
  solutions?: Product[];
  buildCourses?: Product[];
};

const seen = new Set<string>([
  ...baseCatalog.templates.map((i) => i.slug),
  ...baseCatalog.solutions.map((i) => i.slug),
  ...baseCatalog.build.courses.map((i) => i.slug),
]);

const catalog: Catalog = {
  ...baseCatalog,
  templates: [...baseCatalog.templates, ...(extra.templates ?? []).filter((i) => !seen.has(i.slug))],
  solutions: [...baseCatalog.solutions, ...(extra.solutions ?? []).filter((i) => !seen.has(i.slug))],
  build: {
    ...baseCatalog.build,
    courses: [...baseCatalog.build.courses, ...(extra.buildCourses ?? []).filter((i) => !seen.has(i.slug))],
  },
};

export default catalog;
